# For submission purposes only cannot be run without active surreal server + data ingestion

In [1]:
import sys, json
from pathlib import Path

# Make sure project root is on path
sys.path.insert(0, str(Path("..").resolve()))

In [2]:
import pandas as pd

In [3]:
from ingestion.surreal_client import SurrealClient

In [4]:
client = SurrealClient()

In [5]:
def format_query_to_dataframe(query_result):
    if not query_result:
        return "No results found."
    df = pd.DataFrame(query_result)
    if 'id' in df.columns:
        df['id'] = df['id'].astype(str).str.split(':').str[-1]
    return df

def run_and_show(query):
    result = client.http_query(query, False)
    return format_query_to_dataframe(result[0]['result'])

In [6]:
#Retrieve the full names of students who have never attempted any CodeWorkout problems.
run_and_show("""
    SELECT name AS full_name
        FROM student
        WHERE id NOT IN (SELECT VALUE student_id FROM submission);
    """)

[{"result":[{"full_name":"McConney, Brendon"},{"full_name":"Pang, Adam"},{"full_name":"Ghimire, Sami"},{"full_name":"Dukes, Kyrin"},{"full_name":"Gilbert, Andrew"},{"full_name":"Thomas, Aidan"},{"full_name":"Kabir, Ari"},{"full_name":"Conner, Gavin"},{"full_name":"Brown, Demetrius"},{"full_name":"Wegener, Ryan"},{"full_name":"Rich, Connor"},{"full_name":"Singley, Maurice"},{"full_name":"Adigwe, Precious"},{"full_name":"Ali Khan, Mujtaba"},{"full_name":"Anuonye, Martin"},{"full_name":"Asunramu, Oluwatomisin"},{"full_name":"Bachelder, Matthew"},{"full_name":"Benbow, Anna"},{"full_name":"Bentley, Cameron"},{"full_name":"Bruce, Darryl"},{"full_name":"Brummer, Greyson"},{"full_name":"Cancio-Fitzgerald, Mateo"},{"full_name":"Crosby, Ryan"},{"full_name":"Davidson, Emma"},{"full_name":"Diakite, Lansina"},{"full_name":"Dickerson, Summer"},{"full_name":"Dishman, Joe"},{"full_name":"Feldman, Ben"},{"full_name":"Flowers, Josiah"},{"full_name":"Fonseca-Folden, Jax"},{"full_name":"Fowler, Dalton"},{"full_name":"Gallegos Garcia, Andrew"},{"full_name":"German, Jacob"},{"full_name":"Goliber, Kialey"},{"full_name":"Harden, Noah"},{"full_name":"Hernandez, Maya"},{"full_name":"Hilliard, Ryan"},{"full_name":"Horne, Sean"},{"full_name":"Jimenez, Edwin"},{"full_name":"Jones, Elijah"},{"full_name":"Lai, Kristen"},{"full_name":"Lutabingwa, Jonathan"},{"full_name":"Martinez, Hernan"},{"full_name":"Midyette, Caleb"},{"full_name":"Moncada, Danny"},{"full_name":"Morrow, Trace"},{"full_name":"Nariani, Disha"},{"full_name":"Outlaw, Mel"},{"full_name":"Pasupathi, Aravind"},{"full_name":"Patel, Dev"},{"full_name":"Phillips, Sam"},{"full_name":"Ravada, Tanushri"},{"full_name":"Raza, Farhan"},{"full_name":"Reh, Toe"},{"full_name":"Rettke, Lucas"},{"full_name":"Riley, Polan"},{"full_name":"Rolle, Avery"},{"full_name":"Rowe, Caleel"},{"full_name":"Shannon, Nehemiah"},{"full_name":"St. Remy, Michel"},{"full_name":"Stegall, Julian"},{"full_name":"Taban, David"},{"full_name":"Taylor, Benjamin"},{"full_name":"Tundula, Elidad"},{"full_name":"Viveros-Zavaleta, Louis"},{"full_name":"Wane, Raki"},{"full_name":"Wang, Luke"},{"full_name":"Wells, Hunter"},{"full_name":"Yang, Angela"},{"full_name":"York, Jonah"},{"full_name":"Young, Azariah"},{"full_name":"Vallapalli, Soumith"},{"full_name":"Colley, Justin"},{"full_name":"Herrera, Natalia"},{"full_name":"Luongo, Will"},{"full_name":"Alvarado-cruz, Kevin"}],"status":"OK","time":"22.0793068s","type":null}]

               full_name
0      McConney, Brendon
1             Pang, Adam
2          Ghimire, Sami
3           Dukes, Kyrin
4        Gilbert, Andrew
..                   ...
71   Vallapalli, Soumith
72        Colley, Justin
73      Herrera, Natalia
74          Luongo, Will
75  Alvarado-cruz, Kevin

[76 rows x 1 columns]

In [7]:
#Retrieve the full names of students who have the highest total number of submission attempts.
run_and_show("""
    SELECT student_id,type::record('student',student_id).name as full_name,total_attempts
        FROM (SELECT student_id,
        count() AS total_attempts
        FROM submission
        GROUP BY student_id
        ORDER BY total_attempts DESC);
    """)

[{"result":[{"full_name":"Diakite, Lansina","student_id":"77716","total_attempts":3695},{"full_name":"Martinez, Hernan","student_id":"77737","total_attempts":3645},{"full_name":"Yang, Angela","student_id":"77768","total_attempts":3615},{"full_name":"Jimenez, Edwin","student_id":"77733","total_attempts":3519},{"full_name":null,"student_id":"77744","total_attempts":3110},{"full_name":"Jones, Elijah","student_id":"77734","total_attempts":2815},{"full_name":"Nariani, Disha","student_id":"77743","total_attempts":2803},{"full_name":"Benbow, Anna","student_id":"77707","total_attempts":2781},{"full_name":"Fonseca-Folden, Jax","student_id":"77722","total_attempts":2712},{"full_name":"Stegall, Julian","student_id":"77760","total_attempts":2564},{"full_name":"Lai, Kristen","student_id":"77735","total_attempts":2554},{"full_name":"Taylor, Benjamin","student_id":"77762","total_attempts":2474},{"full_name":"Adigwe, Precious","student_id":"77702","total_attempts":2356},{"full_name":"Goliber, Kialey","student_id":"77727","total_attempts":2299},{"full_name":"Reh, Toe","student_id":"77753","total_attempts":2143},{"full_name":"Ali Khan, Mujtaba","student_id":"77703","total_attempts":2111},{"full_name":"St. Remy, Michel","student_id":"77759","total_attempts":2110},{"full_name":"Harden, Noah","student_id":"77729","total_attempts":2081},{"full_name":"Flowers, Josiah","student_id":"77721","total_attempts":2039},{"full_name":"Wells, Hunter","student_id":"77767","total_attempts":2023},{"full_name":"Crosby, Ryan","student_id":"77713","total_attempts":2004},{"full_name":"Fowler, Dalton","student_id":"77723","total_attempts":1988},{"full_name":"Bachelder, Matthew","student_id":"77706","total_attempts":1949},{"full_name":"Lutabingwa, Jonathan","student_id":"77736","total_attempts":1940},{"full_name":"Singley, Maurice","student_id":"70574","total_attempts":1841},{"full_name":"Pasupathi, Aravind","student_id":"77746","total_attempts":1818},{"full_name":"Pang, Adam","student_id":"34870","total_attempts":1804},{"full_name":"Hilliard, Ryan","student_id":"77731","total_attempts":1796},{"full_name":"Wane, Raki","student_id":"77765","total_attempts":1782},{"full_name":"Wang, Luke","student_id":"77766","total_attempts":1771},{"full_name":"Rolle, Avery","student_id":"77756","total_attempts":1767},{"full_name":"Davidson, Emma","student_id":"77715","total_attempts":1746},{"full_name":"Riley, Polan","student_id":"77755","total_attempts":1738},{"full_name":"Brown, Demetrius","student_id":"66612","total_attempts":1719},{"full_name":"Shannon, Nehemiah","student_id":"77758","total_attempts":1710},{"full_name":"McConney, Brendon","student_id":"34723","total_attempts":1706},{"full_name":"Anuonye, Martin","student_id":"77704","total_attempts":1700},{"full_name":"Cancio-Fitzgerald, Mateo","student_id":"77711","total_attempts":1681},{"full_name":"Ravada, Tanushri","student_id":"77751","total_attempts":1667},{"full_name":"Kabir, Ari","student_id":"63126","total_attempts":1667},{"full_name":"Morrow, Trace","student_id":"77742","total_attempts":1645},{"full_name":"Bentley, Cameron","student_id":"77708","total_attempts":1546},{"full_name":"Brummer, Greyson","student_id":"77710","total_attempts":1542},{"full_name":"Colley, Justin","student_id":"78117","total_attempts":1519},{"full_name":"Taban, David","student_id":"77761","total_attempts":1513},{"full_name":"Thomas, Aidan","student_id":"59290","total_attempts":1513},{"full_name":"Hernandez, Maya","student_id":"77730","total_attempts":1509},{"full_name":"Moncada, Danny","student_id":"77741","total_attempts":1508},{"full_name":"Alvarado-cruz, Kevin","student_id":"78334","total_attempts":1503},{"full_name":"Midyette, Caleb","student_id":"77738","total_attempts":1489},{"full_name":"German, Jacob","student_id":"77725","total_attempts":1479},{"full_name":"York, Jonah","student_id":"77769","total_attempts":1447},{"full_name":"Rettke, Lucas","student_id":"77754","total_attempts":1445},{"full_name":"Viveros-Zavaleta, Louis","student_id":"77764","total_attempts":1438},{"full_name":"Wegener, Ryan","student_id":"66625","total_attempts":1423},{"full_name":"Tundula, Elidad","student_id":"77763","total_attempts":1417},{"full_name":"Gallegos Garcia, Andrew","student_id":"77724","total_attempts":1414},{"full_name":"Patel, Dev","student_id":"77747","total_attempts":1403},{"full_name":"Dukes, Kyrin","student_id":"45771","total_attempts":1396},{"full_name":null,"student_id":"77739","total_attempts":1391},{"full_name":"Asunramu, Oluwatomisin","student_id":"77705","total_attempts":1387},{"full_name":"Phillips, Sam","student_id":"77749","total_attempts":1372},{"full_name":"Horne, Sean","student_id":"77732","total_attempts":1356},{"full_name":"Rich, Connor","student_id":"69540","total_attempts":1340},{"full_name":"Gilbert, Andrew","student_id":"57951","total_attempts":1337},{"full_name":"Feldman, Ben","student_id":"77720","total_attempts":1332},{"full_name":"Raza, Farhan","student_id":"77752","total_attempts":1269},{"full_name":"Young, Azariah","student_id":"77770","total_attempts":1254},{"full_name":"Rowe, Caleel","student_id":"77757","total_attempts":1223},{"full_name":"Ghimire, Sami","student_id":"45277","total_attempts":1223},{"full_name":"Outlaw, Mel","student_id":"77745","total_attempts":1149},{"full_name":"Dickerson, Summer","student_id":"77717","total_attempts":1049},{"full_name":"Dishman, Joe","student_id":"77718","total_attempts":1028},{"full_name":"Bruce, Darryl","student_id":"77709","total_attempts":912},{"full_name":"Herrera, Natalia","student_id":"78237","total_attempts":862},{"full_name":"Vallapalli, Soumith","student_id":"77871","total_attempts":537},{"full_name":null,"student_id":"77728","total_attempts":527},{"full_name":"Conner, Gavin","student_id":"66536","total_attempts":451},{"full_name":null,"student_id":"24572","total_attempts":276},{"full_name":null,"student_id":"20241","total_attempts":219},{"full_name":null,"student_id":"13634","total_attempts":211},{"full_name":null,"student_id":"77726","total_attempts":140},{"full_name":null,"student_id":"69461","total_attempts":108},{"full_name":null,"student_id":"77750","total_attempts":108},{"full_name":null,"student_id":"77740","total_attempts":106},{"full_name":null,"student_id":"77719","total_attempts":74},{"full_name":null,"student_id":"77714","total_attempts":3}],"status":"OK","time":"331.3069ms","type":null}]

           full_name student_id  total_attempts
0   Diakite, Lansina      77716            3695
1   Martinez, Hernan      77737            3645
2       Yang, Angela      77768            3615
3     Jimenez, Edwin      77733            3519
4                NaN      77744            3110
..               ...        ...             ...
82               NaN      69461             108
83               NaN      77750             108
84               NaN      77740             106
85               NaN      77719              74
86               NaN      77714               3

[87 rows x 3 columns]

In the above query names are NaN the student id's not appearing in original student mapping file

In [8]:
#Given a Problem ID and a Student SIS Login ID, retrieve the chronological sequence of actions 
# along with their statuses from the student's CodeWorkout interactions.
sis_id = "abenbow1"
problem_id = "915"
run_and_show(f"""
    SELECT server_timestamp, event_type, result, compile_message_type, compile_message
            FROM submission
            WHERE problem_id = '{problem_id}' AND '{sis_id}' IN ->submitted_by->student.sis_id
            ORDER BY server_timestamp ASC;
    """)

[{"result":[{"compile_message":"","compile_message_type":"","event_type":"Run.Program","result":"","server_timestamp":"2024-09-22T19:43:46Z"},{"compile_message":"","compile_message_type":"","event_type":"Compile","result":"Error","server_timestamp":"2024-09-22T19:43:46Z"},{"compile_message":"line 4: error: cannot find symbol: method len()","compile_message_type":"SyntaxError","event_type":"Compile.Error","result":"","server_timestamp":"2024-09-22T19:43:46Z"},{"compile_message":"","compile_message_type":"","event_type":"Compile","result":"Error","server_timestamp":"2024-09-30T15:44:41Z"},{"compile_message":"line 36: error: missing return statement","compile_message_type":"SyntaxError","event_type":"Compile.Error","result":"","server_timestamp":"2024-09-30T15:44:41Z"},{"compile_message":"","compile_message_type":"","event_type":"Run.Program","result":"","server_timestamp":"2024-09-30T15:44:41Z"},{"compile_message":"","compile_message_type":"","event_type":"Run.Program","result":"","server_timestamp":"2024-09-30T15:44:47Z"},{"compile_message":"line 18: error: cannot find symbol: variable i","compile_message_type":"SyntaxError","event_type":"Compile.Error","result":"","server_timestamp":"2024-09-30T15:44:47Z"},{"compile_message":"","compile_message_type":"","event_type":"Compile","result":"Error","server_timestamp":"2024-09-30T15:44:47Z"},{"compile_message":"line 4: error: cannot find symbol: variable len","compile_message_type":"SyntaxError","event_type":"Compile.Error","result":"","server_timestamp":"2024-09-30T15:44:50Z"},{"compile_message":"","compile_message_type":"","event_type":"Compile","result":"Error","server_timestamp":"2024-09-30T15:44:50Z"},{"compile_message":"","compile_message_type":"","event_type":"Run.Program","result":"","server_timestamp":"2024-09-30T15:44:50Z"},{"compile_message":"","compile_message_type":"","event_type":"Run.Program","result":"","server_timestamp":"2024-09-30T15:44:53Z"},{"compile_message":"","compile_message_type":"","event_type":"Compile","result":"Success","server_timestamp":"2024-09-30T15:44:53Z"}],"status":"OK","time":"368.3811ms","type":null}]

,compile_message,compile_message_type,event_type,result,server_timestamp
0,,,Run.Program,,2024-09-22T19:43:46Z
1,,,Compile,Error,2024-09-22T19:43:46Z
2,line 4: error: cannot find symbol: method len(),SyntaxError,Compile.Error,,2024-09-22T19:43:46Z
3,,,Compile,Error,2024-09-30T15:44:41Z
4,line 36: error: missing return statement,SyntaxError,Compile.Error,,2024-09-30T15:44:41Z
5,,,Run.Program,,2024-09-30T15:44:41Z
6,,,Run.Program,,2024-09-30T15:44:47Z
7,line 18: error: cannot find symbol: variable i,SyntaxError,Compile.Error,,2024-09-30T15:44:47Z
8,,,Compile,Error,2024-09-30T15:44:47Z
9,line 4: error: cannot find symbol: variable len,SyntaxError,Compile.Error,,2024-09-30T15:44:50Z
10,,,Compile,Error,2024-09-30T15:44:50Z
11,,,Run.Program,,2024-09-30T15:44:50Z
12,,,Run.Program,,2024-09-30T15:44:53Z
13,,,Compile,Success,2024-09-30T15:44:53Z

In [9]:
#Given a Problem ID, retrieve all learning concepts assessed by that problem
problem_id = "1397"
run_and_show(f"""
    SELECT VALUE concepts
        FROM cw_problem
        WHERE id = cw_problem:`{problem_id}`;
    """)

[{"result":[["SLL Traversal/Search","Algorithm Analysis","Stack Conceptal View","Linked List","O Notation","SLL Removing","SLL Insertion","Stack","Stack Linked List Implementation","Singly Linked List"]],"status":"OK","time":"134.3µs","type":null}]

,0,1,2,3,4,5,6,7,8,9
0,SLL Traversal/Search,Algorithm Analysis,Stack Conceptal View,Linked List,O Notation,SLL Removing,SLL Insertion,Stack,Stack Linked List Implementation,Singly Linked List